### PR TITLE
Added Korean translation for UI

### PR DESCRIPTION
**Pull request by AemonJape**

### CODE REVIEW

**Comment by logchan** [comment]
Thanks for the contribution! I'll work on them within this week.

**Comment by AemonJape** [comment]
I also submitted a pull request for closure Talk resource, and raised an
issue.

**Comment by logchan** [comment]
Yes, I have merged the resource PR (and updated game resources from it) as well.

**Comment by AemonJape** [comment]
I'm working on updates for the updates, but I have heard that Korean names
can also be found in JP server game data.

**Pull request merged**
